# github: JustArchi
patreon: "https://www.patreon.com/camkitties"
custom:
  [
    "https://www.twitch.tv/subs/updownleftdie",
    "https://www.twitch.tv/subs/camkitties",
    "https://paypal.me/jaredkotoff",
    "https://steamcommunity.com/tradeoffer/new/?partner=17031731&token=UO4iqr4V",
  ]
